=head1 NAME

AO3 Downloader

=head1 SYNOPSIS

ao3-download --uid UID [options]

=head1 OPTIONS

=over 12

=item B<--uid>

User ID on AO3. [required]

=item B<--processes>

Processes to run at once.

=item B<--format>

Format to download works in. Valid values are epub (default), mobi, pdf, and html.

=item B<--directory>

Where to download files (default current directory).

=item B<--section>

Section to download. Valid values are bookmarks (default), and works. (Collections and Serieses are not supported at this time).

=back

=head1 DESCRIPTION

B<This program> will download the works found for a section of a given user page.

